Repository wecode-bootcamp-korea/16-2nd-market-ssua-frontend, pull requests merged in 2021-02, with the labels that each got.

#7 [16기 정재윤] 소셜 로그인 버튼 생성 완료, 기능 완료
  package-lock.json
  package.json
  public/index.html
  public/kakao_login_large_narrow.png
  src/Pages/Cart/Cart.js
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/Pages/Social/Social.js
  src/Pages/Social/Social.scss
  src/config.js
Labels: Status: Accepted

#4 [16기 김동하] Mod: details page layout 완료, 목데이터 적용
  public/data/Details.json
  public/data/Inquire.json
  public/data/itemdetail.json
  public/images/check.png
  public/images/dog.jpg
  public/images/promise.png
  src/Pages/Details/Components/Board.js
  src/Pages/Details/Components/Board.scss
  src/Pages/Details/Components/InfoAndCartPut.js
  src/Pages/Details/Components/InfoAndCartPut.scss
  src/Pages/Details/Components/ItemDescription.js
  src/Pages/Details/Components/ItemDescription.scss
  src/Pages/Details/Components/ItemDetailMenu.js
  src/Pages/Details/Components/ItemDetailMenu.scss
  src/Pages/Details/Components/ItemInquire.js
  src/Pages/Details/Components/ItemInquire.scss
  src/Pages/Details/Details.js
  src/Pages/Details/Details.scss
  src/Routes.js
  src/Styles/Common.scss
  src/index.js
Labels: Status: 리뷰 요청

#2 [16기 문규찬] market-ssua 회원가입 페이지 레이아웃 구현완료
  src/Components/signupcompo/Button.js
  src/Components/signupcompo/Input.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Pages/Signup/components/TitleInputButton.js
  src/Pages/Signup/components/TitleInputButton.scss
  src/Pages/Signup/signupData.js
  src/config.js
Labels: Status: 컨플릭트 해결 요청

#6 [16기 이필제] market-ssua 메인페이지&리스트페이지
  package-lock.json
  package.json
  public/data/filters.json
  public/data/items.json
  public/images/img1.jpg
  public/images/img2.jpg
  public/images/insta1.jpg
  public/images/insta2.jpg
  public/images/insta3.jpg
  public/images/insta4.jpg
  public/images/insta5.jpg
  public/images/insta6.jpg
  public/images/insta7.jpg
  public/images/insta8.jpg
  public/images/insta9.jpg
  public/images/main3.png
  public/images/slideimg1.png
  public/images/slideimg2.png
  public/index.html
  src/Components/Button/Button.js
  src/Components/Button/Button.scss
  src/Components/Footer/Footer.scss
  src/Components/Header/Header.js
  src/Components/Item/Item.js
  src/Components/Item/Item.scss
  src/Components/Items/Items.js
  src/Components/Items/Items.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Pagination/Pagination.js
  src/Components/Pagination/Pagination.scss
  src/Components/ProductList/ProductList.js
  src/Components/ProductList/ProductList.scss
  src/Components/Slide/Slide.js
  src/Components/Slide/Slide.scss
  src/Components/SlideInsta/SlideInsta.js
  src/Components/SlideInsta/data/img.js
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/Styles/Common.scss
  src/config.js
Labels: Status: 리뷰 요청

#9 [16기 김동하] 상품상세 페이지 수정완료
  public/data/Details.json
  public/data/Inquire.json
  public/data/itemdetail.json
  public/images/check.png
  public/images/promise.png
  src/Pages/Details/Components/Board.js
  src/Pages/Details/Components/Board.scss
  src/Pages/Details/Components/InfoAndCartPut.js
  src/Pages/Details/Components/InfoAndCartPut.scss
  src/Pages/Details/Components/ItemDescription.js
  src/Pages/Details/Components/ItemDetailMenu.scss
  src/Pages/Details/Components/ItemInquire.js
  src/Pages/Details/Details.js
Labels: Status: 리뷰 요청

#8 [16기 정재윤] 장바구니 페이지 구현 중
  package-lock.json
  public/data/data.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Login/Login.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청
